version: '3'
services:  
    postges:
        container_name: postgres_data
        image: postgres:9.6
        ports: 
            - 5432:5432
        volumes: 
            - ./postgre_db:/var/lib/postgresql/
        env_file: ./.env

    web:
        build: .
        restart: "always"
        ports:
        - "80:8000"
        # command: gunicorn --bind 0.0.0.0 -p 8000 food_stories.wsgi
        volumes:
        - .:/code/
        - ./static/:/code/static/
        - ./media/:/code/media/
        depends_on:
        - "postgres"
        env_file: ./.env